# Generated by Django 3.0.2 on 2020-01-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demo',
            table='demo',
        ),
    ]
